 [target.thumbv7em-none-eabihf]
 runner = "probe-rs run --chip STM32F401RBTx --always-print-stacktrace"

rustflags = [
  "-C", "link-arg=-Tlink.x",
  # Defmt Link Part
  "-C", "link-arg=-Tdefmt.x"
]

[build]
 target = "thumbv7em-none-eabihf"

[env]
DEFMT_LOG = "debug"
