 [target.thumbv6m-none-eabi]
 runner = "probe-rs run --chip STM32C071RBTx --always-print-stacktrace"

rustflags = [
  "-C", "linker=arm-none-eabi-ld",
  "-C", "link-arg=-Tlink.x",
  # Defmt Link Part
  "-C", "link-arg=-Tdefmt.x"
]

[build]
 target = "thumbv6m-none-eabi"
